In [1]:
import numpy as np
import pandas as pd

In [3]:
customer = pd.read_csv('/content/sample_data/customer.csv')
customer.head()


age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        50 non-null     int64 
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB


In [5]:
df = customer.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
X= df.iloc[:,0:2]
X.sample()

review education
8  Average        UG

In [7]:
y= df.iloc[:,-1]
y.sample()

47    Yes
Name: purchased, dtype: object

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [9]:
X_train

review education
29  Average        UG
27     Poor        PG
21  Average        PG
17     Poor        UG
1      Poor        UG
42     Good        PG
38     Good    School
35     Poor    School
23     Good    School
36     Good        UG
16     Poor        UG
13  Average    School
39     Poor        PG
31     Poor    School
10     Good        UG
19     Poor        PG
37  Average        PG
49     Good        UG
28     Poor    School
12     Poor    School
32  Average        UG
7      Poor    School
43     Poor        PG
9      Good        UG
25     Good    School
8   Average        UG
11     Good        UG
30  Average        UG
47     Good        PG
26     Poor        PG
4   Average        UG
48     Good        UG
15     Poor        UG
22     Poor        PG
33     Good        PG
44  Average        UG
18     Good    School
6      Good    School
34  Average    School
46     Poor        PG

In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [12]:
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [13]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [14]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [15]:
X_train

array([[1., 1.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.]])

In [18]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
X_train

array([[1., 1.],
       [0., 2.],
       [1., 2.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [1., 0.],
       [0., 2.]])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0])